/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.UUID;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.util.UserServiceUtil;

public class App {
   

    public static void main(String[] args) {
        System.out.println("Running train booking system....");
        Scanner scanner = new Scanner(System.in);
        int option =0;
        UserBookingService userBookingService;
        try{
            userBookingService = new UserBookingService();
        }
        catch(IOException e){
            e.printStackTrace();
            return;
        }

        while(option != 7){
            System.out.println("choose option");
            System.out.println("1.sign up");
            System.out.println("2.login");
            System.out.println("3.fetch bookings");
            System.out.println("4.search trains");
            System.out.println("5.book a seat");
            System.out.println("6.cancel my booking");
            System.out.println("7.exit the app");

            option = scanner.nextInt();
            Train trainSelectedForBooking = new Train();

            switch(option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter the password to signup");
                    String passwordToSignUp = scanner.next();
                    User userToSignUp = new User(nameToSignUp, passwordToSignUp,
                                        UserServiceUtil.hashPassword(passwordToSignUp),
                                        new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;

                case 2:
                    System.out.println("Enter the username to login");
                    String nameToLogin = scanner.next();
                    System.out.println("enter the password to login");
                    String passwordToLogIn = scanner.next();
                    User userToLogin = new User(nameToLogin,passwordToLogIn,
                                                UserServiceUtil.hashPassword(passwordToLogIn),
                                                new ArrayList<>(),UUID.randomUUID().toString());
                    
                    try{
                        userBookingService = new UserBookingService(userToLogin);
                    }catch(IOException e){
                        return;   
                    }    

                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    System.out.println("type your source station");
                    String source = scanner.next();
                    System.out.println("type your destination station");
                    String destination = scanner.next();
                    List<Train> trains = userBookingService.getTrains(source, destination);
                    int index =1;
                    for(Train t:trains){
                        System.out.println(index + "train id:" + t.getTrainId());
                        for(Map.Entry<String,String> entry : t.getStationTime().entrySet()){
                            System.out.println("station:" + entry.getKey() + "time:" + entry.getValue());
                        }
                    }
                    System.out.println("select any train by typing 1,2,3...");
                    trainSelectedForBooking = trains.get(scanner.nextInt());
                    break;
                case 5:
                    System.out.println("Select a seat out of these seats");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);
                    for (List<Integer> row: seats){
                        for (Integer val: row){
                            System.out.print(val+" ");
                        }
                        System.out.println();
                    }
                    System.out.println("Select the seat by typing the row and column");
                    System.out.println("Enter the row");
                    int row = scanner.nextInt();
                    System.out.println("Enter the column");
                    int col = scanner.nextInt();
                    System.out.println("Booking your seat....");
                    Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col);
                    if(booked.equals(Boolean.TRUE)){
                        System.out.println("Booked! Enjoy your journey");
                    }else{
                        System.out.println("Can't book this seat");
                    }
                    break;
                default:
                    break;
            }

        }
    }
}
